name: Compile Overleaf Document

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    compile-overleaf:
        runs-on: ubuntu-latest
        container: texlive/texlive:latest
        steps:
            - name: Checkout GitHub repository
              uses: actions/checkout@v3

            - name: Clone Overleaf Project
              run: |
                  git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.OVERLEAF_GIT_URL }} overleaf_project

            - name: Install Missing Dependencies
              run: |
                  apt-get update
                  apt-get install -y inkscape

            - name: Compile LaTeX Document with BibTeX
              run: |
                  cd overleaf_project

                  # First LaTeX run
                  latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape main.tex || true

                  # Run BibTeX if a .aux file exists
                  if [ -f main.aux ]; then
                    echo "Running BibTeX for bibliography..."
                    bibtex main
                  fi

                  # Second and third LaTeX runs to resolve citations
                  latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape main.tex
                  latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape main.tex

                  mv main.pdf ../compiled_document.pdf

            - name: Move Compiled PDF to Repository
              run: |
                  mv compiled_document.pdf ./output.pdf

            - name: Commit and Push Compiled Document
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "actions@github.com"
                  git add output.pdf
                  git commit -m "Update compiled PDF from Overleaf"
                  git push
