name: Compile Overleaf Document

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    compile-overleaf:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout GitHub repository
              uses: actions/checkout@v3

            - name: Install LaTeX dependencies
              run: |
                  sudo apt update
                  sudo apt install -y texlive-full latexmk

            - name: Clone Overleaf Project
              run: |
                  git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.OVERLEAF_GIT_URL }} overleaf_project

            - name: Compile LaTeX Document
              run: |
                  cd overleaf_project
                  latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
                  mv main.pdf ../compiled_document.pdf

            - name: Move Compiled PDF to Repository
              run: |
                  mv compiled_document.pdf ./output.pdf

            - name: Commit and Push Compiled Document
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "actions@github.com"
                  git add output.pdf
                  git commit -m "Update compiled PDF from Overleaf"
                  git push
