name: Compile Overleaf Document

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    compile-overleaf:
        runs-on: ubuntu-latest
        container: texlive/texlive:latest
        steps:
            - name: Checkout GitHub repository
              uses: actions/checkout@v3

            - name: Clone Overleaf Project
              run: |
                  echo "::notice::📥 Cloning Overleaf project..."
                  git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.OVERLEAF_GIT_URL }} overleaf_project
                  echo "::notice::✅ Overleaf project cloned successfully"

            - name: Install Missing Dependencies
              run: |
                  echo "::notice::📦 Installing missing dependencies..."
                  apt-get update
                  apt-get install -y inkscape
                  echo "::notice::✅ Dependencies installed successfully"

            - name: Compile LaTeX Document
              run: |
                  cd overleaf_project
                  echo "::notice::🚀 Compiling LaTeX document..."
                  latexmk -pdf -interaction=nonstopmode -halt-on-error -shell-escape main.tex || true

                  mv main.pdf ../thesis.pdf
                  echo "::notice::✅ Compilation complete!"

            - name: Commit and Push to Temporary Branch
              env:
                  GH_PAT: ${{ secrets.GH_PAT }}
              run: |
                  echo "::notice::🚀 Preparing to commit and push PDF..."
                  git config --global user.name "Laurits Bonde"
                  git config --global user.email "lauritsbonde@hotmail.dk"

                  # Set the repository as safe
                  git config --global --add safe.directory /__w/master-thesis/master-thesis

                  # Create and switch to the temporary branch
                  BRANCH_NAME="update-thesis"
                  git checkout -b $BRANCH_NAME || git checkout $BRANCH_NAME

                  # Commit changes
                  git add thesis.pdf
                  git commit -m "Update compiled PDF from Overleaf [skip ci]" || echo "::notice::⚠️ No changes to commit"
                  git push origin $BRANCH_NAME
                  echo "::notice::✅ Changes pushed to branch: $BRANCH_NAME"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GH_PAT }}
                  branch: update-thesis
                  base: master
                  title: '📄 Update Compiled PDF'
                  body: 'Automated update of the compiled LaTeX document.'
                  labels: 'automated, pdf'
                  assignees: lauritsbonde

            - name: Approve Pull Request
              uses: hmarr/auto-approve-action@v3
              with:
                  github-token: ${{ secrets.GH_PAT }}

            - name: Auto-Merge Pull Request
              uses: pascalgn/automerge-action@v0.15.6
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              with:
                  merge-method: squash
                  pull-request-title: '📄 Update Compiled PDF'
                  pull-request-body: 'Automated update of the compiled LaTeX document.'
